// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function make() {
  return "NotAsked";
}

function getData(data) {
  if (typeof data !== "object" || data.TAG !== "Data") {
    return ;
  } else {
    return Caml_option.some(data._0);
  }
}

function getError(data) {
  if (typeof data !== "object" || data.TAG !== "Error") {
    return ;
  } else {
    return data._0;
  }
}

function isNotAsked(data) {
  if (typeof data !== "object" && data === "NotAsked") {
    return true;
  } else {
    return false;
  }
}

function isLoading(data) {
  if (typeof data !== "object" && data === "Loading") {
    return true;
  } else {
    return false;
  }
}

function isData(data) {
  if (typeof data !== "object" || data.TAG !== "Data") {
    return false;
  } else {
    return true;
  }
}

function isError(data) {
  if (typeof data !== "object" || data.TAG !== "Error") {
    return false;
  } else {
    return true;
  }
}

function update(data, f) {
  if (typeof data !== "object" || data.TAG !== "Data") {
    return data;
  } else {
    return {
            TAG: "Data",
            _0: f(data._0)
          };
  }
}

function map(data, f) {
  if (typeof data !== "object" || data.TAG !== "Data") {
    return data;
  } else {
    return {
            TAG: "Data",
            _0: f(data._0)
          };
  }
}

function toData(data) {
  if (typeof data !== "object" || data.TAG !== "Data") {
    return ;
  } else {
    return Caml_option.some(data._0);
  }
}

export {
  make ,
  getData ,
  getError ,
  isNotAsked ,
  isLoading ,
  isData ,
  isError ,
  update ,
  map ,
  toData ,
}
/* No side effect */
